const mongoose=require('mongoose')


const theatreSchema=new mongoose.Schema({
    Name:{
        type:String,
        required:true
    },
    description:{
        type:String,
        required:true  
    },
    rating:{
        type:String,
        required:true
    },
    street:{
        type:String,
        required:true
    },
    city:{
        type:String,
        required:true
    },
    state:{
        type:String,
        required:true
    },
    pincode:{
        type:String,
        required:true
    },
    movies:{
        type:[mongoose.SchemaTypes.ObjectId],
        ref:"Movie"
    },
    createdBy:{
        type:mongoose.SchemaTypes.ObjectId,
        required:true,
        ref:"User"
    },
    bookings:{
        type:[mongoose.SchemaTypes.ObjectId],
        ref:'Booking'
    },
    createdAt:{
        type:Date,
        required:true,
        default:Date.now(),
        immutable:true,
    },
    updatedAt:{
        type:Date,
        required:true,
        default:Date.now()
    }
})

module.exports=mongoose.model("Theatre",theatreSchema)